//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class Activities {
    
    private Activity[] activityField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("Activity")]
    public Activity[] Activity {
        get {
            return this.activityField;
        }
        set {
            this.activityField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class Activity {
    
    private string descriptionField;
    
    private string limitField;
    
    private object itemField;
    
    private string performerField;
    
    private StartMode startModeField;
    
    private FinishMode finishModeField;
    
    private string priorityField;
    
    private Deadline[] deadlineField;
    
    private SimulationInformation simulationInformationField;
    
    private string iconField;
    
    private string documentationField;
    
    private TransitionRestriction[] transitionRestrictionsField;
    
    private ExtendedAttribute[] extendedAttributesField;
    
    private string idField;
    
    private string nameField;
    
    /// <uwagi/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <uwagi/>
    public string Limit {
        get {
            return this.limitField;
        }
        set {
            this.limitField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("BlockActivity", typeof(BlockActivity))]
    [System.Xml.Serialization.XmlElementAttribute("Implementation", typeof(Implementation))]
    [System.Xml.Serialization.XmlElementAttribute("Route", typeof(Route))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <uwagi/>
    public string Performer {
        get {
            return this.performerField;
        }
        set {
            this.performerField = value;
        }
    }
    
    /// <uwagi/>
    public StartMode StartMode {
        get {
            return this.startModeField;
        }
        set {
            this.startModeField = value;
        }
    }
    
    /// <uwagi/>
    public FinishMode FinishMode {
        get {
            return this.finishModeField;
        }
        set {
            this.finishModeField = value;
        }
    }
    
    /// <uwagi/>
    public string Priority {
        get {
            return this.priorityField;
        }
        set {
            this.priorityField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("Deadline")]
    public Deadline[] Deadline {
        get {
            return this.deadlineField;
        }
        set {
            this.deadlineField = value;
        }
    }
    
    /// <uwagi/>
    public SimulationInformation SimulationInformation {
        get {
            return this.simulationInformationField;
        }
        set {
            this.simulationInformationField = value;
        }
    }
    
    /// <uwagi/>
    public string Icon {
        get {
            return this.iconField;
        }
        set {
            this.iconField = value;
        }
    }
    
    /// <uwagi/>
    public string Documentation {
        get {
            return this.documentationField;
        }
        set {
            this.documentationField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("TransitionRestriction", IsNullable=false)]
    public TransitionRestriction[] TransitionRestrictions {
        get {
            return this.transitionRestrictionsField;
        }
        set {
            this.transitionRestrictionsField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ExtendedAttribute", IsNullable=false)]
    public ExtendedAttribute[] ExtendedAttributes {
        get {
            return this.extendedAttributesField;
        }
        set {
            this.extendedAttributesField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class BlockActivity {
    
    private string blockIdField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string BlockId {
        get {
            return this.blockIdField;
        }
        set {
            this.blockIdField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class Implementation {
    
    private object[] itemsField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("No", typeof(No))]
    [System.Xml.Serialization.XmlElementAttribute("SubFlow", typeof(SubFlow))]
    [System.Xml.Serialization.XmlElementAttribute("Tool", typeof(Tool))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class No {
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class SubFlow {
    
    private string[] actualParametersField;
    
    private string idField;
    
    private SubFlowExecution executionField;
    
    private bool executionFieldSpecified;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ActualParameter", IsNullable=false)]
    public string[] ActualParameters {
        get {
            return this.actualParametersField;
        }
        set {
            this.actualParametersField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public SubFlowExecution Execution {
        get {
            return this.executionField;
        }
        set {
            this.executionField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ExecutionSpecified {
        get {
            return this.executionFieldSpecified;
        }
        set {
            this.executionFieldSpecified = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
public enum SubFlowExecution {
    
    /// <uwagi/>
    ASYNCHR,
    
    /// <uwagi/>
    SYNCHR,
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class Tool {
    
    private string[] actualParametersField;
    
    private string descriptionField;
    
    private ExtendedAttribute[] extendedAttributesField;
    
    private string idField;
    
    private ToolType typeField;
    
    private bool typeFieldSpecified;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ActualParameter", IsNullable=false)]
    public string[] ActualParameters {
        get {
            return this.actualParametersField;
        }
        set {
            this.actualParametersField = value;
        }
    }
    
    /// <uwagi/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ExtendedAttribute", IsNullable=false)]
    public ExtendedAttribute[] ExtendedAttributes {
        get {
            return this.extendedAttributesField;
        }
        set {
            this.extendedAttributesField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ToolType Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TypeSpecified {
        get {
            return this.typeFieldSpecified;
        }
        set {
            this.typeFieldSpecified = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class ExtendedAttribute {
    
    private System.Xml.XmlElement[] itemsField;
    
    private string[] textField;
    
    private string nameField;
    
    private string valueField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
public enum ToolType {
    
    /// <uwagi/>
    APPLICATION,
    
    /// <uwagi/>
    PROCEDURE,
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class Route {
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class StartMode {
    
    private object itemField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("Automatic", typeof(Automatic))]
    [System.Xml.Serialization.XmlElementAttribute("Manual", typeof(Manual))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class Automatic {
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class Manual {
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class FinishMode {
    
    private object itemField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("Automatic", typeof(Automatic))]
    [System.Xml.Serialization.XmlElementAttribute("Manual", typeof(Manual))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class Deadline {
    
    private object deadlineConditionField;
    
    private object exceptionNameField;
    
    private DeadlineExecution executionField;
    
    private bool executionFieldSpecified;
    
    /// <uwagi/>
    public object DeadlineCondition {
        get {
            return this.deadlineConditionField;
        }
        set {
            this.deadlineConditionField = value;
        }
    }
    
    /// <uwagi/>
    public object ExceptionName {
        get {
            return this.exceptionNameField;
        }
        set {
            this.exceptionNameField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public DeadlineExecution Execution {
        get {
            return this.executionField;
        }
        set {
            this.executionField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ExecutionSpecified {
        get {
            return this.executionFieldSpecified;
        }
        set {
            this.executionFieldSpecified = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
public enum DeadlineExecution {
    
    /// <uwagi/>
    ASYNCHR,
    
    /// <uwagi/>
    SYNCHR,
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class SimulationInformation {
    
    private string costField;
    
    private TimeEstimation timeEstimationField;
    
    private SimulationInformationInstantiation instantiationField;
    
    private bool instantiationFieldSpecified;
    
    /// <uwagi/>
    public string Cost {
        get {
            return this.costField;
        }
        set {
            this.costField = value;
        }
    }
    
    /// <uwagi/>
    public TimeEstimation TimeEstimation {
        get {
            return this.timeEstimationField;
        }
        set {
            this.timeEstimationField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public SimulationInformationInstantiation Instantiation {
        get {
            return this.instantiationField;
        }
        set {
            this.instantiationField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool InstantiationSpecified {
        get {
            return this.instantiationFieldSpecified;
        }
        set {
            this.instantiationFieldSpecified = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class TimeEstimation {
    
    private string waitingTimeField;
    
    private string workingTimeField;
    
    private string durationField;
    
    /// <uwagi/>
    public string WaitingTime {
        get {
            return this.waitingTimeField;
        }
        set {
            this.waitingTimeField = value;
        }
    }
    
    /// <uwagi/>
    public string WorkingTime {
        get {
            return this.workingTimeField;
        }
        set {
            this.workingTimeField = value;
        }
    }
    
    /// <uwagi/>
    public string Duration {
        get {
            return this.durationField;
        }
        set {
            this.durationField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
public enum SimulationInformationInstantiation {
    
    /// <uwagi/>
    ONCE,
    
    /// <uwagi/>
    MULTIPLE,
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class TransitionRestriction {
    
    private Join joinField;
    
    private Split splitField;
    
    /// <uwagi/>
    public Join Join {
        get {
            return this.joinField;
        }
        set {
            this.joinField = value;
        }
    }
    
    /// <uwagi/>
    public Split Split {
        get {
            return this.splitField;
        }
        set {
            this.splitField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class Join {
    
    private JoinType typeField;
    
    private bool typeFieldSpecified;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public JoinType Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TypeSpecified {
        get {
            return this.typeFieldSpecified;
        }
        set {
            this.typeFieldSpecified = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
public enum JoinType {
    
    /// <uwagi/>
    AND,
    
    /// <uwagi/>
    XOR,
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class Split {
    
    private TransitionRef[] transitionRefsField;
    
    private SplitType typeField;
    
    private bool typeFieldSpecified;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("TransitionRef", IsNullable=false)]
    public TransitionRef[] TransitionRefs {
        get {
            return this.transitionRefsField;
        }
        set {
            this.transitionRefsField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public SplitType Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TypeSpecified {
        get {
            return this.typeFieldSpecified;
        }
        set {
            this.typeFieldSpecified = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class TransitionRef {
    
    private string idField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
public enum SplitType {
    
    /// <uwagi/>
    AND,
    
    /// <uwagi/>
    XOR,
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class ActivitySet {
    
    private Activity[] activitiesField;
    
    private Transition[] transitionsField;
    
    private string idField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Activity", IsNullable=false)]
    public Activity[] Activities {
        get {
            return this.activitiesField;
        }
        set {
            this.activitiesField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Transition", IsNullable=false)]
    public Transition[] Transitions {
        get {
            return this.transitionsField;
        }
        set {
            this.transitionsField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class Transition {
    
    private Condition conditionField;
    
    private string descriptionField;
    
    private ExtendedAttribute[] extendedAttributesField;
    
    private string idField;
    
    private string fromField;
    
    private string toField;
    
    private string nameField;
    
    /// <uwagi/>
    public Condition Condition {
        get {
            return this.conditionField;
        }
        set {
            this.conditionField = value;
        }
    }
    
    /// <uwagi/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ExtendedAttribute", IsNullable=false)]
    public ExtendedAttribute[] ExtendedAttributes {
        get {
            return this.extendedAttributesField;
        }
        set {
            this.extendedAttributesField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string From {
        get {
            return this.fromField;
        }
        set {
            this.fromField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string To {
        get {
            return this.toField;
        }
        set {
            this.toField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class Condition {
    
    private Xpression[] itemsField;
    
    private string[] textField;
    
    private ConditionType typeField;
    
    private bool typeFieldSpecified;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("Xpression")]
    public Xpression[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ConditionType Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TypeSpecified {
        get {
            return this.typeFieldSpecified;
        }
        set {
            this.typeFieldSpecified = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class Xpression {
    
    private System.Xml.XmlElement[] itemsField;
    
    private string[] textField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
public enum ConditionType {
    
    /// <uwagi/>
    CONDITION,
    
    /// <uwagi/>
    OTHERWISE,
    
    /// <uwagi/>
    EXCEPTION,
    
    /// <uwagi/>
    DEFAULTEXCEPTION,
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class ActivitySets {
    
    private ActivitySet[] activitySetField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("ActivitySet")]
    public ActivitySet[] ActivitySet {
        get {
            return this.activitySetField;
        }
        set {
            this.activitySetField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class ActualParameters {
    
    private string[] actualParameterField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("ActualParameter")]
    public string[] ActualParameter {
        get {
            return this.actualParameterField;
        }
        set {
            this.actualParameterField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class Application {
    
    private string descriptionField;
    
    private object itemField;
    
    private ExtendedAttribute[] extendedAttributesField;
    
    private string idField;
    
    private string nameField;
    
    /// <uwagi/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("ExternalReference", typeof(ExternalReference))]
    [System.Xml.Serialization.XmlElementAttribute("FormalParameters", typeof(FormalParameters))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ExtendedAttribute", IsNullable=false)]
    public ExtendedAttribute[] ExtendedAttributes {
        get {
            return this.extendedAttributesField;
        }
        set {
            this.extendedAttributesField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class ExternalReference {
    
    private string xrefField;
    
    private string locationField;
    
    private string namespaceField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string xref {
        get {
            return this.xrefField;
        }
        set {
            this.xrefField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string location {
        get {
            return this.locationField;
        }
        set {
            this.locationField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string @namespace {
        get {
            return this.namespaceField;
        }
        set {
            this.namespaceField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class FormalParameters {
    
    private FormalParameter[] formalParameterField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("FormalParameter")]
    public FormalParameter[] FormalParameter {
        get {
            return this.formalParameterField;
        }
        set {
            this.formalParameterField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class FormalParameter {
    
    private DataType dataTypeField;
    
    private string descriptionField;
    
    private string idField;
    
    private string indexField;
    
    private FormalParameterMode modeField;
    
    public FormalParameter() {
        this.modeField = FormalParameterMode.IN;
    }
    
    /// <uwagi/>
    public DataType DataType {
        get {
            return this.dataTypeField;
        }
        set {
            this.dataTypeField = value;
        }
    }
    
    /// <uwagi/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string Index {
        get {
            return this.indexField;
        }
        set {
            this.indexField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(FormalParameterMode.IN)]
    public FormalParameterMode Mode {
        get {
            return this.modeField;
        }
        set {
            this.modeField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class DataType {
    
    private object itemField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("ArrayType", typeof(ArrayType))]
    [System.Xml.Serialization.XmlElementAttribute("BasicType", typeof(BasicType))]
    [System.Xml.Serialization.XmlElementAttribute("DeclaredType", typeof(DeclaredType))]
    [System.Xml.Serialization.XmlElementAttribute("EnumerationType", typeof(EnumerationType))]
    [System.Xml.Serialization.XmlElementAttribute("ExternalReference", typeof(ExternalReference))]
    [System.Xml.Serialization.XmlElementAttribute("ListType", typeof(ListType))]
    [System.Xml.Serialization.XmlElementAttribute("RecordType", typeof(RecordType))]
    [System.Xml.Serialization.XmlElementAttribute("SchemaType", typeof(SchemaType))]
    [System.Xml.Serialization.XmlElementAttribute("UnionType", typeof(UnionType))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class ArrayType {
    
    private object itemField;
    
    private string lowerIndexField;
    
    private string upperIndexField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("ArrayType", typeof(ArrayType))]
    [System.Xml.Serialization.XmlElementAttribute("BasicType", typeof(BasicType))]
    [System.Xml.Serialization.XmlElementAttribute("DeclaredType", typeof(DeclaredType))]
    [System.Xml.Serialization.XmlElementAttribute("EnumerationType", typeof(EnumerationType))]
    [System.Xml.Serialization.XmlElementAttribute("ExternalReference", typeof(ExternalReference))]
    [System.Xml.Serialization.XmlElementAttribute("ListType", typeof(ListType))]
    [System.Xml.Serialization.XmlElementAttribute("RecordType", typeof(RecordType))]
    [System.Xml.Serialization.XmlElementAttribute("SchemaType", typeof(SchemaType))]
    [System.Xml.Serialization.XmlElementAttribute("UnionType", typeof(UnionType))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string LowerIndex {
        get {
            return this.lowerIndexField;
        }
        set {
            this.lowerIndexField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string UpperIndex {
        get {
            return this.upperIndexField;
        }
        set {
            this.upperIndexField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class BasicType {
    
    private BasicTypeType typeField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public BasicTypeType Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
public enum BasicTypeType {
    
    /// <uwagi/>
    STRING,
    
    /// <uwagi/>
    FLOAT,
    
    /// <uwagi/>
    INTEGER,
    
    /// <uwagi/>
    REFERENCE,
    
    /// <uwagi/>
    DATETIME,
    
    /// <uwagi/>
    BOOLEAN,
    
    /// <uwagi/>
    PERFORMER,
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class DeclaredType {
    
    private string idField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class EnumerationType {
    
    private EnumerationValue[] enumerationValueField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("EnumerationValue")]
    public EnumerationValue[] EnumerationValue {
        get {
            return this.enumerationValueField;
        }
        set {
            this.enumerationValueField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class EnumerationValue {
    
    private string nameField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class ListType {
    
    private object itemField;
    
    private ItemChoiceType itemElementNameField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("ArrayType", typeof(ArrayType))]
    [System.Xml.Serialization.XmlElementAttribute("BasicType", typeof(BasicType))]
    [System.Xml.Serialization.XmlElementAttribute("DeclaredType", typeof(DeclaredType))]
    [System.Xml.Serialization.XmlElementAttribute("EnumerationType", typeof(EnumerationType))]
    [System.Xml.Serialization.XmlElementAttribute("ExternalReference", typeof(ExternalReference))]
    [System.Xml.Serialization.XmlElementAttribute("ListType", typeof(ListType))]
    [System.Xml.Serialization.XmlElementAttribute("RecordType", typeof(RecordType))]
    [System.Xml.Serialization.XmlElementAttribute("SchemaType", typeof(SchemaType))]
    [System.Xml.Serialization.XmlElementAttribute("UnionType", typeof(UnionType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class RecordType {
    
    private Member[] memberField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("Member")]
    public Member[] Member {
        get {
            return this.memberField;
        }
        set {
            this.memberField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class Member {
    
    private object itemField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("ArrayType", typeof(ArrayType))]
    [System.Xml.Serialization.XmlElementAttribute("BasicType", typeof(BasicType))]
    [System.Xml.Serialization.XmlElementAttribute("DeclaredType", typeof(DeclaredType))]
    [System.Xml.Serialization.XmlElementAttribute("EnumerationType", typeof(EnumerationType))]
    [System.Xml.Serialization.XmlElementAttribute("ExternalReference", typeof(ExternalReference))]
    [System.Xml.Serialization.XmlElementAttribute("ListType", typeof(ListType))]
    [System.Xml.Serialization.XmlElementAttribute("RecordType", typeof(RecordType))]
    [System.Xml.Serialization.XmlElementAttribute("SchemaType", typeof(SchemaType))]
    [System.Xml.Serialization.XmlElementAttribute("UnionType", typeof(UnionType))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class SchemaType {
    
    private System.Xml.XmlElement[] anyField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class UnionType {
    
    private Member[] memberField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("Member")]
    public Member[] Member {
        get {
            return this.memberField;
        }
        set {
            this.memberField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IncludeInSchema=false)]
public enum ItemChoiceType {
    
    /// <uwagi/>
    ArrayType,
    
    /// <uwagi/>
    BasicType,
    
    /// <uwagi/>
    DeclaredType,
    
    /// <uwagi/>
    EnumerationType,
    
    /// <uwagi/>
    ExternalReference,
    
    /// <uwagi/>
    ListType,
    
    /// <uwagi/>
    RecordType,
    
    /// <uwagi/>
    SchemaType,
    
    /// <uwagi/>
    UnionType,
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
public enum FormalParameterMode {
    
    /// <uwagi/>
    IN,
    
    /// <uwagi/>
    OUT,
    
    /// <uwagi/>
    INOUT,
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class Applications {
    
    private Application[] applicationField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("Application")]
    public Application[] Application {
        get {
            return this.applicationField;
        }
        set {
            this.applicationField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class ConformanceClass {
    
    private ConformanceClassGraphConformance graphConformanceField;
    
    private bool graphConformanceFieldSpecified;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ConformanceClassGraphConformance GraphConformance {
        get {
            return this.graphConformanceField;
        }
        set {
            this.graphConformanceField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool GraphConformanceSpecified {
        get {
            return this.graphConformanceFieldSpecified;
        }
        set {
            this.graphConformanceFieldSpecified = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
public enum ConformanceClassGraphConformance {
    
    /// <uwagi/>
    FULL_BLOCKED,
    
    /// <uwagi/>
    LOOP_BLOCKED,
    
    /// <uwagi/>
    NON_BLOCKED,
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class DataField {
    
    private DataType dataTypeField;
    
    private string initialValueField;
    
    private string lengthField;
    
    private string descriptionField;
    
    private ExtendedAttribute[] extendedAttributesField;
    
    private string idField;
    
    private string nameField;
    
    private DataFieldIsArray isArrayField;
    
    public DataField() {
        this.isArrayField = DataFieldIsArray.FALSE;
    }
    
    /// <uwagi/>
    public DataType DataType {
        get {
            return this.dataTypeField;
        }
        set {
            this.dataTypeField = value;
        }
    }
    
    /// <uwagi/>
    public string InitialValue {
        get {
            return this.initialValueField;
        }
        set {
            this.initialValueField = value;
        }
    }
    
    /// <uwagi/>
    public string Length {
        get {
            return this.lengthField;
        }
        set {
            this.lengthField = value;
        }
    }
    
    /// <uwagi/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ExtendedAttribute", IsNullable=false)]
    public ExtendedAttribute[] ExtendedAttributes {
        get {
            return this.extendedAttributesField;
        }
        set {
            this.extendedAttributesField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(DataFieldIsArray.FALSE)]
    public DataFieldIsArray IsArray {
        get {
            return this.isArrayField;
        }
        set {
            this.isArrayField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
public enum DataFieldIsArray {
    
    /// <uwagi/>
    TRUE,
    
    /// <uwagi/>
    FALSE,
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class DataFields {
    
    private DataField[] dataFieldField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("DataField")]
    public DataField[] DataField {
        get {
            return this.dataFieldField;
        }
        set {
            this.dataFieldField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class ExtendedAttributes {
    
    private ExtendedAttribute[] extendedAttributeField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("ExtendedAttribute")]
    public ExtendedAttribute[] ExtendedAttribute {
        get {
            return this.extendedAttributeField;
        }
        set {
            this.extendedAttributeField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class ExternalPackage {
    
    private ExtendedAttribute[] extendedAttributesField;
    
    private string hrefField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ExtendedAttribute", IsNullable=false)]
    public ExtendedAttribute[] ExtendedAttributes {
        get {
            return this.extendedAttributesField;
        }
        set {
            this.extendedAttributesField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string href {
        get {
            return this.hrefField;
        }
        set {
            this.hrefField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class ExternalPackages {
    
    private ExternalPackage[] externalPackageField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("ExternalPackage")]
    public ExternalPackage[] ExternalPackage {
        get {
            return this.externalPackageField;
        }
        set {
            this.externalPackageField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class Package {
    
    private PackageHeader packageHeaderField;
    
    private RedefinableHeader redefinableHeaderField;
    
    private ConformanceClass conformanceClassField;
    
    private Script scriptField;
    
    private ExternalPackage[] externalPackagesField;
    
    private TypeDeclaration[] typeDeclarationsField;
    
    private Participant[] participantsField;
    
    private Application[] applicationsField;
    
    private DataField[] dataFieldsField;
    
    private WorkflowProcess[] workflowProcessesField;
    
    private ExtendedAttribute[] extendedAttributesField;
    
    private string idField;
    
    private string nameField;
    
    /// <uwagi/>
    public PackageHeader PackageHeader {
        get {
            return this.packageHeaderField;
        }
        set {
            this.packageHeaderField = value;
        }
    }
    
    /// <uwagi/>
    public RedefinableHeader RedefinableHeader {
        get {
            return this.redefinableHeaderField;
        }
        set {
            this.redefinableHeaderField = value;
        }
    }
    
    /// <uwagi/>
    public ConformanceClass ConformanceClass {
        get {
            return this.conformanceClassField;
        }
        set {
            this.conformanceClassField = value;
        }
    }
    
    /// <uwagi/>
    public Script Script {
        get {
            return this.scriptField;
        }
        set {
            this.scriptField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ExternalPackage", IsNullable=false)]
    public ExternalPackage[] ExternalPackages {
        get {
            return this.externalPackagesField;
        }
        set {
            this.externalPackagesField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("TypeDeclaration", IsNullable=false)]
    public TypeDeclaration[] TypeDeclarations {
        get {
            return this.typeDeclarationsField;
        }
        set {
            this.typeDeclarationsField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Participant", IsNullable=false)]
    public Participant[] Participants {
        get {
            return this.participantsField;
        }
        set {
            this.participantsField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Application", IsNullable=false)]
    public Application[] Applications {
        get {
            return this.applicationsField;
        }
        set {
            this.applicationsField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("DataField", IsNullable=false)]
    public DataField[] DataFields {
        get {
            return this.dataFieldsField;
        }
        set {
            this.dataFieldsField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("WorkflowProcess", IsNullable=false)]
    public WorkflowProcess[] WorkflowProcesses {
        get {
            return this.workflowProcessesField;
        }
        set {
            this.workflowProcessesField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ExtendedAttribute", IsNullable=false)]
    public ExtendedAttribute[] ExtendedAttributes {
        get {
            return this.extendedAttributesField;
        }
        set {
            this.extendedAttributesField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class PackageHeader {
    
    private string xPDLVersionField;
    
    private string vendorField;
    
    private string createdField;
    
    private string descriptionField;
    
    private string documentationField;
    
    private string priorityUnitField;
    
    private string costUnitField;
    
    /// <uwagi/>
    public string XPDLVersion {
        get {
            return this.xPDLVersionField;
        }
        set {
            this.xPDLVersionField = value;
        }
    }
    
    /// <uwagi/>
    public string Vendor {
        get {
            return this.vendorField;
        }
        set {
            this.vendorField = value;
        }
    }
    
    /// <uwagi/>
    public string Created {
        get {
            return this.createdField;
        }
        set {
            this.createdField = value;
        }
    }
    
    /// <uwagi/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <uwagi/>
    public string Documentation {
        get {
            return this.documentationField;
        }
        set {
            this.documentationField = value;
        }
    }
    
    /// <uwagi/>
    public string PriorityUnit {
        get {
            return this.priorityUnitField;
        }
        set {
            this.priorityUnitField = value;
        }
    }
    
    /// <uwagi/>
    public string CostUnit {
        get {
            return this.costUnitField;
        }
        set {
            this.costUnitField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class RedefinableHeader {
    
    private string authorField;
    
    private string versionField;
    
    private string codepageField;
    
    private string countrykeyField;
    
    private string[] responsiblesField;
    
    private RedefinableHeaderPublicationStatus publicationStatusField;
    
    private bool publicationStatusFieldSpecified;
    
    /// <uwagi/>
    public string Author {
        get {
            return this.authorField;
        }
        set {
            this.authorField = value;
        }
    }
    
    /// <uwagi/>
    public string Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <uwagi/>
    public string Codepage {
        get {
            return this.codepageField;
        }
        set {
            this.codepageField = value;
        }
    }
    
    /// <uwagi/>
    public string Countrykey {
        get {
            return this.countrykeyField;
        }
        set {
            this.countrykeyField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Responsible", IsNullable=false)]
    public string[] Responsibles {
        get {
            return this.responsiblesField;
        }
        set {
            this.responsiblesField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public RedefinableHeaderPublicationStatus PublicationStatus {
        get {
            return this.publicationStatusField;
        }
        set {
            this.publicationStatusField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PublicationStatusSpecified {
        get {
            return this.publicationStatusFieldSpecified;
        }
        set {
            this.publicationStatusFieldSpecified = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
public enum RedefinableHeaderPublicationStatus {
    
    /// <uwagi/>
    UNDER_REVISION,
    
    /// <uwagi/>
    RELEASED,
    
    /// <uwagi/>
    UNDER_TEST,
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class Script {
    
    private string typeField;
    
    private string versionField;
    
    private string grammarField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Grammar {
        get {
            return this.grammarField;
        }
        set {
            this.grammarField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class TypeDeclaration {
    
    private BasicType basicTypeField;
    
    private DeclaredType declaredTypeField;
    
    private SchemaType schemaTypeField;
    
    private ExternalReference externalReferenceField;
    
    private RecordType recordTypeField;
    
    private UnionType unionTypeField;
    
    private EnumerationType enumerationTypeField;
    
    private ArrayType arrayTypeField;
    
    private ListType listTypeField;
    
    private string descriptionField;
    
    private ExtendedAttribute[] extendedAttributesField;
    
    private string idField;
    
    private string nameField;
    
    /// <uwagi/>
    public BasicType BasicType {
        get {
            return this.basicTypeField;
        }
        set {
            this.basicTypeField = value;
        }
    }
    
    /// <uwagi/>
    public DeclaredType DeclaredType {
        get {
            return this.declaredTypeField;
        }
        set {
            this.declaredTypeField = value;
        }
    }
    
    /// <uwagi/>
    public SchemaType SchemaType {
        get {
            return this.schemaTypeField;
        }
        set {
            this.schemaTypeField = value;
        }
    }
    
    /// <uwagi/>
    public ExternalReference ExternalReference {
        get {
            return this.externalReferenceField;
        }
        set {
            this.externalReferenceField = value;
        }
    }
    
    /// <uwagi/>
    public RecordType RecordType {
        get {
            return this.recordTypeField;
        }
        set {
            this.recordTypeField = value;
        }
    }
    
    /// <uwagi/>
    public UnionType UnionType {
        get {
            return this.unionTypeField;
        }
        set {
            this.unionTypeField = value;
        }
    }
    
    /// <uwagi/>
    public EnumerationType EnumerationType {
        get {
            return this.enumerationTypeField;
        }
        set {
            this.enumerationTypeField = value;
        }
    }
    
    /// <uwagi/>
    public ArrayType ArrayType {
        get {
            return this.arrayTypeField;
        }
        set {
            this.arrayTypeField = value;
        }
    }
    
    /// <uwagi/>
    public ListType ListType {
        get {
            return this.listTypeField;
        }
        set {
            this.listTypeField = value;
        }
    }
    
    /// <uwagi/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ExtendedAttribute", IsNullable=false)]
    public ExtendedAttribute[] ExtendedAttributes {
        get {
            return this.extendedAttributesField;
        }
        set {
            this.extendedAttributesField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class Participant {
    
    private ParticipantType participantTypeField;
    
    private string descriptionField;
    
    private ExternalReference externalReferenceField;
    
    private ExtendedAttribute[] extendedAttributesField;
    
    private string idField;
    
    private string nameField;
    
    /// <uwagi/>
    public ParticipantType ParticipantType {
        get {
            return this.participantTypeField;
        }
        set {
            this.participantTypeField = value;
        }
    }
    
    /// <uwagi/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <uwagi/>
    public ExternalReference ExternalReference {
        get {
            return this.externalReferenceField;
        }
        set {
            this.externalReferenceField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ExtendedAttribute", IsNullable=false)]
    public ExtendedAttribute[] ExtendedAttributes {
        get {
            return this.extendedAttributesField;
        }
        set {
            this.extendedAttributesField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class ParticipantType {
    
    private ParticipantTypeType typeField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ParticipantTypeType Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
public enum ParticipantTypeType {
    
    /// <uwagi/>
    RESOURCE_SET,
    
    /// <uwagi/>
    RESOURCE,
    
    /// <uwagi/>
    ROLE,
    
    /// <uwagi/>
    ORGANIZATIONAL_UNIT,
    
    /// <uwagi/>
    HUMAN,
    
    /// <uwagi/>
    SYSTEM,
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class WorkflowProcess {
    
    private ProcessHeader processHeaderField;
    
    private RedefinableHeader redefinableHeaderField;
    
    private FormalParameters formalParametersField;
    
    private DataField[] dataFieldsField;
    
    private Participant[] participantsField;
    
    private Application[] applicationsField;
    
    private ActivitySet[] activitySetsField;
    
    private Activity[] activitiesField;
    
    private Transition[] transitionsField;
    
    private ExtendedAttribute[] extendedAttributesField;
    
    private string idField;
    
    private string nameField;
    
    private WorkflowProcessAccessLevel accessLevelField;
    
    private bool accessLevelFieldSpecified;
    
    /// <uwagi/>
    public ProcessHeader ProcessHeader {
        get {
            return this.processHeaderField;
        }
        set {
            this.processHeaderField = value;
        }
    }
    
    /// <uwagi/>
    public RedefinableHeader RedefinableHeader {
        get {
            return this.redefinableHeaderField;
        }
        set {
            this.redefinableHeaderField = value;
        }
    }
    
    /// <uwagi/>
    public FormalParameters FormalParameters {
        get {
            return this.formalParametersField;
        }
        set {
            this.formalParametersField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("DataField", IsNullable=false)]
    public DataField[] DataFields {
        get {
            return this.dataFieldsField;
        }
        set {
            this.dataFieldsField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Participant", IsNullable=false)]
    public Participant[] Participants {
        get {
            return this.participantsField;
        }
        set {
            this.participantsField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Application", IsNullable=false)]
    public Application[] Applications {
        get {
            return this.applicationsField;
        }
        set {
            this.applicationsField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ActivitySet", IsNullable=false)]
    public ActivitySet[] ActivitySets {
        get {
            return this.activitySetsField;
        }
        set {
            this.activitySetsField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Activity", IsNullable=false)]
    public Activity[] Activities {
        get {
            return this.activitiesField;
        }
        set {
            this.activitiesField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Transition", IsNullable=false)]
    public Transition[] Transitions {
        get {
            return this.transitionsField;
        }
        set {
            this.transitionsField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ExtendedAttribute", IsNullable=false)]
    public ExtendedAttribute[] ExtendedAttributes {
        get {
            return this.extendedAttributesField;
        }
        set {
            this.extendedAttributesField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public WorkflowProcessAccessLevel AccessLevel {
        get {
            return this.accessLevelField;
        }
        set {
            this.accessLevelField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AccessLevelSpecified {
        get {
            return this.accessLevelFieldSpecified;
        }
        set {
            this.accessLevelFieldSpecified = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class ProcessHeader {
    
    private string createdField;
    
    private string descriptionField;
    
    private string priorityField;
    
    private string limitField;
    
    private string validFromField;
    
    private string validToField;
    
    private TimeEstimation timeEstimationField;
    
    private ProcessHeaderDurationUnit durationUnitField;
    
    private bool durationUnitFieldSpecified;
    
    /// <uwagi/>
    public string Created {
        get {
            return this.createdField;
        }
        set {
            this.createdField = value;
        }
    }
    
    /// <uwagi/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <uwagi/>
    public string Priority {
        get {
            return this.priorityField;
        }
        set {
            this.priorityField = value;
        }
    }
    
    /// <uwagi/>
    public string Limit {
        get {
            return this.limitField;
        }
        set {
            this.limitField = value;
        }
    }
    
    /// <uwagi/>
    public string ValidFrom {
        get {
            return this.validFromField;
        }
        set {
            this.validFromField = value;
        }
    }
    
    /// <uwagi/>
    public string ValidTo {
        get {
            return this.validToField;
        }
        set {
            this.validToField = value;
        }
    }
    
    /// <uwagi/>
    public TimeEstimation TimeEstimation {
        get {
            return this.timeEstimationField;
        }
        set {
            this.timeEstimationField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ProcessHeaderDurationUnit DurationUnit {
        get {
            return this.durationUnitField;
        }
        set {
            this.durationUnitField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DurationUnitSpecified {
        get {
            return this.durationUnitFieldSpecified;
        }
        set {
            this.durationUnitFieldSpecified = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
public enum ProcessHeaderDurationUnit {
    
    /// <uwagi/>
    Y,
    
    /// <uwagi/>
    M,
    
    /// <uwagi/>
    D,
    
    /// <uwagi/>
    h,
    
    /// <uwagi/>
    m,
    
    /// <uwagi/>
    s,
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
public enum WorkflowProcessAccessLevel {
    
    /// <uwagi/>
    PUBLIC,
    
    /// <uwagi/>
    PRIVATE,
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class Participants {
    
    private Participant[] participantField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("Participant")]
    public Participant[] Participant {
        get {
            return this.participantField;
        }
        set {
            this.participantField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class Responsibles {
    
    private string[] responsibleField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("Responsible")]
    public string[] Responsible {
        get {
            return this.responsibleField;
        }
        set {
            this.responsibleField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class TransitionRefs {
    
    private TransitionRef[] transitionRefField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("TransitionRef")]
    public TransitionRef[] TransitionRef {
        get {
            return this.transitionRefField;
        }
        set {
            this.transitionRefField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class TransitionRestrictions {
    
    private TransitionRestriction[] transitionRestrictionField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("TransitionRestriction")]
    public TransitionRestriction[] TransitionRestriction {
        get {
            return this.transitionRestrictionField;
        }
        set {
            this.transitionRestrictionField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class Transitions {
    
    private Transition[] transitionField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("Transition")]
    public Transition[] Transition {
        get {
            return this.transitionField;
        }
        set {
            this.transitionField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class TypeDeclarations {
    
    private TypeDeclaration[] typeDeclarationField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("TypeDeclaration")]
    public TypeDeclaration[] TypeDeclaration {
        get {
            return this.typeDeclarationField;
        }
        set {
            this.typeDeclarationField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wfmc.org/2002/XPDL1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wfmc.org/2002/XPDL1.0", IsNullable=false)]
public partial class WorkflowProcesses {
    
    private WorkflowProcess[] workflowProcessField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("WorkflowProcess")]
    public WorkflowProcess[] WorkflowProcess {
        get {
            return this.workflowProcessField;
        }
        set {
            this.workflowProcessField = value;
        }
    }
}
